## [exp2liveatlas_0GenericAffine.mat,1] and exp2liveatlas_1InverseWarp.nii.gz are among the file generated by 'antsRegistration.sh".
## [To_fixed_0GenericAffine.mat,1] and To_fixed_1InverseWarp.nii.gz are the file for the conversion from the live template to the fixed one.

antsApplyTransformsToPoints -d 3  -i input.csv -o output.csv -t [exp2liveatlas_0GenericAffine.mat,1] -t exp2liveatlas_1InverseWarp.nii.gz  -t [To_fixed_0GenericAffine.mat,1] -t To_fixed_1InverseWarp.nii.gz
